# Generated by Django 3.2.2 on 2021-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210508_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('Staff', 'Staff'), ('User', 'User')], max_length=50, null=True),
        ),
    ]
